apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasklist-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tasklist
  template:
    metadata:
      labels:
        app: tasklist
    spec:
      containers:
        - name: tasklist
          image: ghcr.io/team-m4/tasklist-app:0bf57d898a51b285dc0f988410e7c5c2406510fc
          ports:
            - containerPort: 8080
