apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasklist-app
  namespace: default
  labels:
    app: tasklist
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tasklist
  template:
    metadata:
      labels:
        app: tasklist
    spec:
      containers:
        - name: tasklist
          image: ghcr.io/team-m4/tasklist-app:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/tasklist_db
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: tasklist-db-secret
                  key: DB_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: tasklist-db-secret
                  key: DB_PASSWORD
      imagePullSecrets:
        - name: ghcr-secret
